name: Build & Test
on:
  pull_request:
    branches: [ "main", "dev" ]


jobs:
  compile:
    runs-on: ubuntu-latest

    env:
      VCPKG_BINARY_SOURCES: "clear;files,${{github.workspace}}/.vcpkg-bincache,readwrite"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache vcpkg binaries
        uses: actions/cache@v4
        with:
          path: .vcpkg-bincache
          key: vcpkg-${{runner.os}}-${{hashFiles('vcpkg.json')}}
          restore-keys: vcpkg-${{runner.os}}-

      - name: Set up CMake
        uses: jwlawson/actions-setup-cmake@v2
        with:
          cmake-version: "4.0.0"

      # 2. Run vcpkg (Sets up the tool and handles caching automatically)
      - name: Run vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          # This tells the action where to find or clone vcpkg
          vcpkgDirectory: "${{ github.workspace }}/vcpkg"

      #3. Configure CMake pointing to the vcpkg toolchain file
      - name: Configure CMake
        run: |
          cmake --preset vcpkg-preset

      - name: Build
        run: |
          cmake --build build vcpkg-preset

      - name: Test
        run: ctest --test-dir build --output-on-failure


